const products = [
  {
    _id: '1',
    name: 'besos',
    image: '/images/besos.jpeg',
    description: 'remera ',
    brand: 're-meras',
    price: 1000,
  },
  {
    _id: '2',
    name: 'besos-negra',
    image: '/images/besos-negra.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 1000,
  },
  {
    _id: '3',
    name: 'corazon',
    image: '/images/corazon.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 1000,
  },
  {
    _id: '4',
    name: 'frase-cortazar-blanca',
    image: '/images/frase-cortazar-blanca.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 1200,
  },
  {
    _id: '5',
    name: 'frase-cortazar-negra',
    image: '/images/frase-cortazar-negra.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 1200,
  },

  {
    _id: '6',
    name: 'marca-maldita-blanca',
    image: '/images/marca-maldita-blanca.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 1200,
  },

  {
    _id: '7',
    name: 'rolling-negra',
    image: '/images/rolling-negra.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 2000,
  },
  {
    _id: '8',
    name: 'rolling-blanca',
    image: '/images/rolling-blanca.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 2000,
  },
  {
    _id: '9',
    name: 'ogi-blanca',
    image: '/images/ogi-blanca.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 2000,
  },

  {
    _id: '10',
    name: 'ogi-negra',
    image: '/images/ogi-negra.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 2000,
  },
  {
    _id: '11',
    name: 'todo-cambia-negra',
    image: '/images/todo-cambia-negra.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 2000,
  },
  {
    _id: '12',
    name: 'todo-cambia-blanca',
    image: '/images/todo-cambia-blanca.jpeg',
    description: 'remera',
    brand: 're-meras',
    price: 2000,
  },
  {
    _id: '13',
    name: 'wild-blanca',
    image: '/images/wild-blanca.jpeg',
    description: 'remera',
    brand: 're-meras',
  },
  {
    _id: '14',
    name: 'wild-negra',
    image: '/images/wild-negra.jpeg',
    description: 'remera',
    brand: 're-meras',
  },
];

export default products;
